### ISSUE TITLE
Mozzi suddenly stopped compiling - something about a missing file: #include <compat/twi.h>

### ISSUE THREAD

**Issue by joaoorecchia** [sensorium/Mozzi#26]
Using a Teensy 3.5, I started going through the Mozzi tutorials and examples, everything was fine. Went back 2 days later and suddenly nothing will compile. I've tried fully uninstalling Arduino, Teensyduino and Mozzi and reinstalling different versions. Always the same result. Basic Arduino sketches are uploading so I'm guessing it's not a board/port issue.

Arduino: 1.6.12 (Mac OS X), TD: 1.31, Board: "Teensy 3.5, Serial, 120 MHz, US English"

WARNING: Category 'Sound' in library Mozzi is not valid. Setting to 'Uncategorized'
In file included from /Users/joaoorecchia/Documents/Arduino/libraries/Mozzi/twi_nonblock.cpp:12:0:
/Users/joaoorecchia/Documents/Arduino/libraries/Mozzi/twi_nonblock.h:17:24: fatal error: compat/twi.h: No such file or directory
 #include <compat/twi.h>
                        ^
compilation terminated.
Error compiling for board Teensy 3.5.

**Comment by tfry-git** [comment]
This should be fixed by now (either by https://github.com/sensorium/Mozzi/commit/d7772b82e27be92139a1879c7aaf932a9a58f760#diff-49be6e41059a1dd149cade9d95f31f99), or by the recently added "real" Teensy 3.5 support (https://github.com/sensorium/Mozzi/pull/44).

If problems persist, please open a new issue ticket.
