### ISSUE TITLE
WARNING: Category 'Audio' in library Mozzi is not valid. Setting to 'Uncategorized'

### ISSUE THREAD

**Issue by pen2pen2** [sensorium/Mozzi#30]
Just downloaded the latest release. Unfortunately, this error shows up:

WARNING: Category 'Audio' in library Mozzi is not valid. Setting to 'Uncategorized'

Will it affect anything? If so, how can this be fixed?

**Comment by sensorium** [comment]
Doesn't seem to affect anything - I don't know if it might be because
Arduino doesn't have a category for Audio?  Or something wrong in
library.properties?
Here's the library.properties file:

name=Mozzi
version=1.0.3
author=Tim Barrass and contributors as documented in source, and at
https://github.com/sensorium/Mozzi/graphs/contributors
maintainer=Tim Barrass <faveflave@gmail.com>
sentence=Sound synthesis library for Arduino
paragraph=With Mozzi, you can construct sounds using familiar synthesis
units like oscillators, delays, filters and envelopes.
category=Audio
url=https://sensorium.github.io/Mozzi/
architectures=*
dot_a_linkage=false
includes=MozziGuts.h

**Comment by hectorlee** [comment]
The Arduino library does not have a "Audio" category. 

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

> category - if present, one of these: "Display", "Communication", "Signal Input/Output", "Sensors", "Device Control", "Timing", "Data Storage", "Data Processing", "Other"

Seems like the most appropriate category should be Signal Input/Output.

**Comment by sensorium** [comment]
Thanks Hector

**Comment by orbitinstasis** [comment]
May i ask, if there was a fix for this, as the warning tends to be a bit of a bother.

**Comment by sensorium** [comment]
Edit library.properties so it reads:
category=Signal Input/Output

as suggested by Hector in this thread.

It'll be fixed in the next release, if it's not in the most recent one.

**Comment by per1234** [comment]
This was fixed by https://github.com/sensorium/Mozzi/commit/f89629862bcdd61d47f243c881832bf03c8d70f0.
