### ISSUE TITLE
ESP32 support

### ISSUE THREAD

**Issue by JacobErnst98** [sensorium/Mozzi#58]
Thanks for the ESP8266 Support but the ESP32 is better in every manner.

**Comment by joknjokn** [comment]
Hi. Do you know how to make it work with ESP32? Or maybe a similar library with ESP32 support?
And I agree. ESP32 is dual core and more, so it would be so great to have support for this.

**Comment by mangtronix** [comment]
Has anyone made progress on this? Thanks.

**Comment by tfry-git** [comment]
Dear folks. Support for new architectures depends on someone working with those architectures to care enough to invest somewhere between 10 and 20 hours of work. Personally, I do own one ESP32, but I'm using it for a different project, and the ESP32 is a bit too expensive to have a couple, just in case. Yet more importantly, I do not have a personal use for Mozzi on ESP32, currently.

You can either: a) Try to do this yourself. It is not really all that hard. Since Mozzi has been ported to several different architectures, already, you should be able to figure out the basic steps, involved. One of the hardest parts is testing, actually. b) Offer a bounty for this, hoping somebody else will do the work for you.

**Comment by mangtronix** [comment]
I have basic sound output working on ESP32 using the ESP8266Audio library (https://github.com/earlephilhower/ESP8266Audio). That library is licensed GPL, so I believe it's not possible to integrate with Mozzi because the Mozzi Creative Commons license is not compatible. Is there any possibility of making Mozzi dual license with a GPL compatible license?

**Comment by zircothc** [comment]
Hello. I ported Mozzi to Arduino Due with a very good result. It was really easy.
Now I've ported Mozzi to ESP32 I2S DAC (PT8211) but audio output is a bit dirty. 
May be timer issue. I'm very busy next days and cannot test it . If somebody want it, library patched files are in zip attached included DUE patch (DueTimer library needed to run).
[Mozzi_ESP32_and_DUE_files.zip](https://github.com/sensorium/Mozzi/files/3168326/Mozzi_ESP32_and_DUE_files.zip)

**Comment by tobozo** [comment]
looks like another angle https://github.com/bitluni/ULPSoundESP32

**Comment by mangtronix** [comment]
Maybe he needs that for his application (I didn't watch the video) but I
have a hard time believing that sending audio to the DAC via DMA (the usual
way on ESP32) isn't the right answer. There's not that much needed for an
audio driver... basically you need to set up the I2S and then fill a ring
buffer with the audio samples. The samples in the ring buffer can be sent
to the DAC in the background, clocked by the DAC itself.

**Comment by tobozo** [comment]
I've only had acceptable sound using an external DAC or the ULP, the Tetris demo is very convincing

**Comment by wyan** [comment]
Did anyone manage to do some progress on ESP32 support lately?

**Comment by mangtronix** [comment]
I got sound output working using this library (https://github.com/earlephilhower/ESP8266Audio), but unfortunately the licenses are not compatible so I can't release the code. In the end it wasn't toooo hard... basically you just send the samples to the audio library and you can cut out a lot of the more esoteric Mozzi code.

**Comment by wyan** [comment]
Thanks! I'm not as familiar with the internals of Mozzi as I'd like, so I'm not sure I follow you. Perhaps posting a code patch without merging it could be a way to respect both licences? That way it's the end user who's applying the patch and that's ok as long as they are not distributing the code or a product derived from it?

**Comment by zircothc** [comment]
> Did anyone manage to do some progress on ESP32 support lately?
Here yo can find patched files to support ESP32 with a very good sound.
https://groups.google.com/forum/#!topic/mozzi-users/qw2nIkcVaZE

**Comment by tfry-git** [comment]
ESP32 is now supported in the main lib with several output modes.
